language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"

install:
  - python setup.py install

before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then cd build/lib/volt/test; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then cd volt/test; fi"

script:
  - nosetests .
