# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

before_install:
    - pip install -r requirements-dev.txt

install:
    - python setup.py install
    - pip install codecov==2.0.5

script:
    - py.test -vv --cov --cov-config .coveragerc --flake8 tests volt

after_success:
    - codecov
