language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install coveralls --use-wheel
  - python setup.py develop
  - pip install -r dev-requirements.txt

script:
  - py.test --cov-report term --cov volt tests/

after_success:
  - coveralls
