# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

before_install:
    - pip install -r requirements-dev.txt

install:
    - python setup.py install

script:
    - py.test -vv --cov=volt --flake8 tests volt
